server:
  port: 8080
spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
      #ddl-auto: create
    properties.hibernate.use_sql_comments: true
    properties.hibernate.format_sql: true

  sql:
    init:
      platform: h2
      #mode: always
      mode: never
      continue-on-error: true
      schema-locations: classpath:/db/schema-h2.sql
      data-locations: classpath:/db/data-h2.sql

logging:
  config: classpath:log4j2.xml
